### ISSUE TITLE
Allow a parameter for the content of the file.

### ISSUE THREAD

**Issue by 1WindowsPuppetAdmin** [voxpupuli/puppet-sslcertificate#101]
Similar to the kpn-sslcertificate module, allow a paramter for the content of the file. Ex: Base-64 encoded representation of a pfx file. This means we don't have to rely on the cert being stored locally somewhere. Obviously, clean up the file after we use it.

This can be encrypted and put into hiera.

**Comment by liger1978** [comment]
@1WindowsPuppetAdmin FYI, I've written a module that can take PEM strings in hiera and place a pfx file on the system: https://forge.puppet.com/liger1978/pemtopfx

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
