### ISSUE TITLE
sslcertificate depends on old puppetlabs-powershell module and blocks its upgrade

### ISSUE THREAD

**Issue by michalmiddleton** [voxpupuli/puppet-sslcertificate#106]
## Affected Puppet, Ruby, OS and module versions/distributions

    Puppet: Agent 6.15.0
    Ruby: built in
    Distribution: opensource puppet agent
    Module version: 4.1.0

## How to reproduce (e.g Puppet code you use)
`puppet module upgrade puppetlabs-powershell`

## What are you seeing
Powershell module upgrade is blocked because:
`'puppet-sslcertificate' (v4.1.0) requires 'puppetlabs-powershell' (>= 1.1.1 < 3.0.0)`
Current version of powershell is 3.0.1

## Any additional information you'd like to impart
Unless explicitly needed, can you please update the requirement of puppetlabs-powershell? Thank you

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
