### ISSUE TITLE
Code Manager can't install module version 4.1.0 due to invalid version number in metadata.json

### ISSUE THREAD

**Issue by rychannel** [voxpupuli/puppet-sslcertificate#109]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## What are you seeing

Invalid version number in metadata.json

 Failed to evaluate /etc/puppetlabs/code-staging/environments/windows_test/Puppetfile\nOriginal exception:\nInvalid 'version' field in metadata.json: version string cannot be parsed as a valid Semantic Version\nERROR\t -> Failed to evaluate /etc/puppetlabs/code-staging/environments/windows_test/Puppetfile\nOriginal exception:\nInvalid 'version' field in metadata.json: version string cannot be parsed as a valid Semantic Version

**Comment by kenyon** [comment]
Sounds like you are trying to install directly from the master branch of this GitHub repository. I believe the version is deliberately unparseable because it is a prerelease.

**Comment by rychannel** [comment]
Nope not at all. Mod line in my puppet file pointing at the latest version listed on the forge

**Comment by rychannel** [comment]
Actually this is a weird config problem I found on my end.  For some reason code manager decided to choke on one of my modules version numbers and then didn’t delete it before trying to deploy the environment when I removed it from the puppet file.
