### ISSUE TITLE
Support 'puppetlabs-powershell', '5.0.0'

### ISSUE THREAD

**Issue by cmchoi2000** [voxpupuli/puppet-sslcertificate#115]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 2021.4.0
- Ruby:
- Distribution:
- Module version: 4.1.0

## How to reproduce (e.g Puppet code you use)
**How to request this module to upgrade to 'puppetlabs-powershell', '5.0.0'**

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
