### ISSUE TITLE
Passing a wrong password for a pfx file created with OpenSSL 3 fails silently on Windows 2019

### ISSUE THREAD

**Issue by kev-in-shu** [voxpupuli/puppet-sslcertificate#116]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Puppet 6
- Ruby:
- Distribution:
- Module version: 4.1.0

## Issue

Passing a wrong password fails silently on Windows 2019.
Tested it also on Windows 2012 R2, and it fails as expected.

My pfx file contains 1 certificate and its private key + 1 root certificate.

I tested the powershell code outside of Puppet, and I get the same results: silently failing on Windows 2019, failing as expected on Windows 2012 R2.

**Comment by kev-in-shu** [comment]
Here is the pure Powershell I ran on Windows 2019, with its output

```
PS Cert:\LocalMachine\My\> $pfx = new-object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
PS Cert:\LocalMachine\My\> $pfx.Import("D:\temp\mycertificate.pfx","wrong password",'MachineKeySet,Exportable,PersistKeySet')
PS Cert:\LocalMachine\My\> $pfx

Thumbprint                                Subject
----------                                -------
xxXXxxXXxxXXxxXXxxXXxxXXxxXXxxXXxxXXxxXX  CN=dom validation Secure Server CA, O=CA Limited, L=Kent, S=Leeds, C=GB
xxXXxxXXxxXXxxXXxxXXxxXXxxXXxxXXxxXXxxXX  CN=www.mycert.com

```


Here is the same script ran on Windows 2012 R2, with its error output (correct behavior)

```
PS Cert:\LocalMachine\my> $pfx = new-object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
PS Cert:\LocalMachine\my> $pfx.Import("D:\temp\mycertificate.pfx","wrong password",'MachineKeySet,Exportable,PersistKeySet')
Exception calling "Import" with "3" argument(s): "Unknown error "-1073741762"."
At line:1 char:1
+ $pfx.Import("D:\temp\mycertificate.pfx","wrong passwo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicException

PS Cert:\LocalMachine\my> $pfx
PS Cert:\LocalMachine\my>


```

**Comment by kev-in-shu** [comment]
After further testing, this difference in behavior only happens on PFX files created with OpenSSL 3.0

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
