### ISSUE TITLE
Support 'puppetlabs-stdlib', '8.5.0'

### ISSUE THREAD

**Issue by cmchoi2000** [voxpupuli/puppet-sslcertificate#117]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 202.7.2
- Ruby:
- Distribution:
- Module version: 4.1.0

## What are you seeing
'puppet-sslcertificate' (v4.1.0) requires 'puppetlabs-stdlib' (>= 4.13.1 < 7.0.0).

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
