### ISSUE TITLE
Intermediate store isn't closed after import.

### ISSUE THREAD

**Issue by mswolfe** [voxpupuli/puppet-sslcertificate#12]
The "CA" or intermediate store is never closed in templates/import.ps1.erb.  Line 42 closes the $store object, but the $intermediatestore object is never closed.  In my testing this has meant that the intermediate CA and root CA certifcates are never truly added to the "CA" store.

Is it intended that only the certificate from the PFX file designated by the thumbprint is installed?

**Comment by pillarsdotnet** [comment]
Let's assume that it isn't.  Submitted: #98

**Comment by mswolfe** [comment]
Woot!  Thanks everyone!
