### ISSUE TITLE
Need ability to specify friendlyName attribute during cert installation

### ISSUE THREAD

**Issue by paulmsullivan** [voxpupuli/puppet-sslcertificate#13]
During installation of SSL certificates on Windows (at least if using PowerShell and System.Security.Cryptography.X509Certificates.X509Certificate2) it is possible to supply the friendlyName attribute.  I have a need to install certificates that were not issued with friendlyName.  Today we do this with a PowerShell script that adds this attribute before adding the System.Security.Cryptography.X509Certificates.X509Certificate2 object to the store System.Security.Cryptography.X509Certificates.X509Store("My","LocalMachine").

Can you add the friendlyname attribute to be passed into this module?

**Comment by mrsofia** [comment]
This would be a very useful feature and is the main reason why we can't use this library in its current state. Friendly names are absolutely necessary for development and differentiation so I think this is a pretty glaring omission.

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
