### ISSUE TITLE
forge page is confusing

### ISSUE THREAD

**Issue by tgm4883** [voxpupuli/puppet-sslcertificate#14]
The puppet forge page for this module is confusing (see https://forge.puppetlabs.com/puppet/sslcertificate )

In one place it has the following example, with the weird ticks and puppet 

``` puppet
sslcertificate { "Install-PFX-Certificate" :
  name       => 'mycert.pfx',
  password   => 'password123',
  location   => 'C:\',
  thumbprint => '07E5C1AF7F5223CB975CC29B5455642F5570798B'
}
```

Under usage it says to use "sslcert". 

Looking at the module, the actual definition is to use "sslcertificate"

**Comment by ghoneycutt** [comment]
Closing as this no longer seems to be the case in the README. Please re-open with a PR to the docs if I missed what you are talking about. Thanks!
