### ISSUE TITLE
Importing a single root cert breaks inspect

### ISSUE THREAD

**Issue by doksner** [voxpupuli/puppet-sslcertificate#15]
I'm trying to use this module to import our own internal Cert Authority cert (using a .crt file) and I think because it's just a single cert it is breaking the test of the .Count property of $pfx ($pfx.Count is undefined).  I assume this is because with a single cert, $pfx is a single object not an array.  Because it's not found, the test for the expected number of installed certs is false, causing the module to run import every single time.  Is there some way to either force a single instance to become an array or a reliable way to detect the difference between a single object, an array of objects, and no objects (assuming that's what is returned if no valid certs are found)?

**Comment by rammaram06** [comment]
@doksner  were you able to find a fix for this? I am having same issue, import runs every single time

**Comment by igalic** [comment]
can we start with an rspec test to repro the behaviour?

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
