### ISSUE TITLE
Password being required for both .cer and .p7b CA import

### ISSUE THREAD

**Issue by paulmsullivan** [voxpupuli/puppet-sslcertificate#16]
I am trying to import a (Comodo) CA certificate using this module.  I exported it in both P7B and CER formats (since I experienced this error first with P7B I then tried the CER).  I can import either in Windows by right-click>import without a password being required.

When I try to import them with this module I am getting this error about needing a password:

```
  Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Must
  pass password to Sslcertificate[xxxxxxxxxxxxxxxx] at /etc/puppet
  labs/code/environments/production/modules/profile/manifests/windows/certauths.pp
  :15 on node xxxxxxxxxxxxxxxxxxxxx
```

Here is the way I am accessing this module:

``` puppet
  sslcertificate { "Install-Comodo-High-Assurance-CA" :
    name       => 'COMODO.CA.sn-46cb.p7b',
    location   => "C:\\Support\\CAs",
    store_dir  => 'CA',
    root_store => 'LocalMachine',
    thumbprint => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    require => File["Comodo-High-Assurance-CA-File"],
  }
```

I basically am looking for this certificate to be imported into Trusted Root Certification Authorities.

I would open a case with Puppet support but I don't think they support these community modules?

Let me know if there is more information that would be helpful?

Thank you!

**Comment by mendhak** [comment]
Did you try with a password empty string?    If that fails then maybe force a password on it when exporting?

    sslcertificate { "Install-Comodo-High-Assurance-CA" :
        name => 'COMODO.CA.sn-46cb.p7b',
        password => "",
        location => "C:\Support\CAs",
        store_dir => 'CA',
        root_store => 'LocalMachine',
        thumbprint => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        require => File["Comodo-High-Assurance-CA-File"],
    }

Or consider adding a password in.

Also to get it into the Trusted Root CA, I did:

    root_store => 'LocalMachine',
    store_dir  => 'Root'

**Comment by jordigg** [comment]
Tried with `password => ""` and doesn't work. Will try to look into it. In case we use password there's another issue open (#7) to avoid plain text strings. On the log you can see those password being used while importing the certificate.

**Comment by orelydia** [comment]
In example p7b, there is no password and the import.ps1 script doesn't use a password for the p7b format.
Why make it mandatory when it isn't used for p7b format certificates?

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
