### ISSUE TITLE
Doesn't import Private Keys with Wildcard Cert

### ISSUE THREAD

**Issue by rychannel** [voxpupuli/puppet-sslcertificate#25]
I had to modify this module so that it would import the private keys with my wildcard cert (.pfx file)

**Comment by hpAB** [comment]
im having the same issue, was there a fix for this?

**Comment by hpAB** [comment]
Ah got it ! 
line 18 add MachineKeySet

$pfx.import("<%= @location %>\\<%= @name %>","<%= @password %>","Exportable,MachineKeySet,PersistKeySet")

**Comment by rychannel** [comment]
That's way nicer than my fix

**Comment by chughesvf** [comment]
wouldn't this solution from hpAB force the exportable flag? not necessarily desirable

**Comment by pillarsdotnet** [comment]
Looks like this issue should be closed.

**Comment by rychannel** [comment]
Looks like the module has been updated to fix the problem.  The updates I applied years ago to my own copy of the module are no longer necessary.
