### ISSUE TITLE
PrivateKey directory is filling up

### ISSUE THREAD

**Issue by slmcfarland81** [voxpupuli/puppet-sslcertificate#33]
I'm using this module with puppet 3.8 and 4.6 to install certs on 2012r2 from .pfx and .cer files. Every time Inspect.ps1 is run the .pfx certificate is loaded and seems to leave a private key artifact on disk. I just looked at a machine running this module for a single cert for a year - 21,000+ files in there!

Would it be reasonable to assume if the cert matching the thumbprint is installed that the intermediate certs are there too? This would make it possible to just look up by thumbprint without loading into memory (and on disk for privateKeys)

**Comment by ouberlord** [comment]
Just coming across this issue as well, and it poses a relatively significant problem for me.  I see that this issue has had no traction, in the meantime have you found any means of addressing the issue?

**Comment by cmezzett** [comment]
Submitted PR#70 to resolve this issue
