### ISSUE TITLE
Cannot import the same certificate file into more than one store

### ISSUE THREAD

**Issue by ouberlord** [voxpupuli/puppet-sslcertificate#37]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Latest
- Distribution: CentOS (puppet master), Windows Server 2012 R2 (puppet agent)
- Module version: Latest

## How to reproduce (e.g Puppet code you use)
Any manifest that has multiple uses of `sslcertificate` with the same `name` value.

## What are you seeing
The following Agent output:

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Cannot alias Sslcertificate[Import sso.domainname.com into Local Machine /Other People] to ["sso.domainname.com.pfx"] at /etc/puppetlabs/code/environments/production/modules/abp_app/manifests/sslcerts.pp:45; resource ["Sslcertificate", "sso.domainname.com.pfx"] already declared at /etc/puppetlabs/code/environments/production/modules/abp_app/manifests/sslcerts.pp:5 at /etc/puppetlabs/code/environments/production/modules/abp_app/manifests/sslcerts.pp:45:3 on node nodename.domainname.local

## What behaviour did you expect instead
That the same certificate file could be imported into each of the two locations.

## Output log
See "What are you seeing" above.

## Any additional information you'd like to impart
If it is not possible to have multiple uses of the same `name `value, could an array be used for the `store_dir` value instead?

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
