### ISSUE TITLE
Invalid resource type sslcertificate

### ISSUE THREAD

**Issue by hpAB** [voxpupuli/puppet-sslcertificate#40]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppe
t::Parser::AST::Resource failed with error ArgumentError: Invalid resource type
sslcertificate at /etc/puppet/modules/...pp

**Comment by hpAB** [comment]
resolved by

https://github.com/voxpupuli/puppet-sslcertificate/pull/29

**Comment by pillarsdotnet** [comment]
Should this issue be closed?

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
