### ISSUE TITLE
Incorrect thumbprint does not result in failure

### ISSUE THREAD

**Issue by wholtz** [voxpupuli/puppet-sslcertificate#53]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.4
- Ruby:  2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- Distribution: Ubuntu 16.04
- Module version: 2.2.0

## How to reproduce (e.g Puppet code you use)

sslcertificate { "Install MyCert" :
        name       => 'MyCert.crt',
        location   => 'C:\temp',
        store_dir  => 'Root',
        root_store => 'LocalMachine',
        password   => '',
        thumbprint => 'FOOBAR',
        require    => File['C:\temp\MyCert.crt'],
}

MyCert.crt contains a single root level certificate with no intermediates. The thumbprint value does not match this certificate.

## What are you seeing

MyCert gets installed into CA rather than Root. The puppet run terminates without an error. 

## What behaviour did you expect instead

MyCert would not get installed and the puppet run would display an error, "Thumbprint 'FOOBAR' was not found n MyCert.crt."

## Output log

Notice: /Stage[main]/win_instrument::Config/Sslcertificate[Install MyCert]/File[inspect-MyCert.crt-certificate.ps1]/content:

Info: Computing checksum on file C:/temp/inspect-MyCert.crt.ps1
Info: /Stage[main]/win_instrument::Config/Sslcertificate[Install MyCert]/File[inspect-MyCert.crt-certificate.ps1]: Filebucketed C:/temp/inspect-MyCert.crt.ps1 to puppet with sum 5079a791910bf353a5206d74cbb21bde
Notice: /Stage[main]/win_instrument::Config/Sslcertificate[Install MyCert]/File[inspect-MyCert.crt-certificate.ps1]/content: content changed '{md5}5079a791910bf353a5206d74cbb21bde' to '{md5}5b0ce7c056d180dcd99b3004282e96bf'
Notice: /Stage[main]/win_instrument::Config/Sslcertificate[Install MyCert]/File[import-MyCert.crt-certificate.ps1]/content:

Info: Computing checksum on file C:/temp/import-MyCert.crt.ps1
Info: /Stage[main]/win_instrument::Config/Sslcertificate[Install MyCert]/File[import-MyCert.crt-certificate.ps1]: Filebucketed C:/temp/import-MyCert.crt.ps1 to puppet with sum 577c9b403e7cfda694853dd4d4240140
Notice: /Stage[main]/win_instrument::Config/Sslcertificate[Install MyCert]/File[import-MyCert.crt-certificate.ps1]/content: content changed '{md5}577c9b403e7cfda694853dd4d4240140' to '{md5}8eab18b06d4642ca8bc6b4afde4fd47c'
Notice: /Stage[main]/win_instrument::Config/Sslcertificate[Install MyCert]/Exec[Install-MyCert.crt-SSLCert]/returns: executed successfully

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
