### ISSUE TITLE
Note differences in providers based on import method

### ISSUE THREAD

**Issue by rdev5** [voxpupuli/puppet-sslcertificate#62]
Citing [lines 30-33](https://github.com/voxpupuli/puppet-sslcertificate/blob/master/templates/import.ps1.erb#L30-L33) of `import.ps1.erb`, it should be noted that the `X509Store.Add` method will result in the certificate being imported with "Microsoft Enhanced Cryptographic Provider v1.0" as evidenced by running the command `certutil -store My`. This is the same behavior as using the "Install PFX..." option from the context menu or importing it using `certlm.msc`.

This *differs* from the `Import-PfxCertificate` PowerShell command, however, which imports the same *.pfx with "Microsoft Software Key Store Provider."

Please consider extending the script to support either as an option in the event this detail becomes relevant in certain environments.

Additional resources:
- [Microsoft Software Key Storage Provider](https://msdn.microsoft.com/en-us/library/windows/desktop/bb931355(v=vs.85).aspx#Microsoft_Software_Key_Storage_Provider)
- [Microsoft Enhanced Cryptographic Provider v1.0](https://msdn.microsoft.com/en-us/library/windows/desktop/bb931357(v=vs.85).aspx#Microsoft_Enhanced_Cryptographic_Provider_v1.0)

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
