### ISSUE TITLE
Allow managing SSL certificates without a password

### ISSUE THREAD

**Issue by natemccurdy** [voxpupuli/puppet-sslcertificate#64]
The `password` parameter requires a String of length 1 which means it's impossible to manage a cert without a password. Sometime, in dev environments, you may want to have a cert without a password.

https://github.com/voxpupuli/puppet-sslcertificate/blob/v3.2.0/manifests/init.pp#L82

In previous versions of the module, this worked (<= `2.2.0`). As of `3.0.0` this broke due to the strict typing.

**Comment by dlabko** [comment]
Version 3.3.0 worked well.
It is now able to add certificates without password.
Tested on Windows 2012 R2.
Question: is there a way to remove a certificate?

**Comment by alexjfisher** [comment]
@dlabko It doesn’t look like the type provides a mechanism for removing a cert. PRs welcome! :)
