### ISSUE TITLE
eyaml question

### ISSUE THREAD

**Issue by gworley82** [voxpupuli/puppet-sslcertificate#71]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## Any additional information you'd like to impart

I am trying to use hiera with eyaml to secure my ssl certificate password. The sslcertificate.thumbprint is working correctly, but when I change the sslcertificate.password to a hiera lookup, it fails. I know my syntax is correct because the thumbprint lookup works, and I even tried an unencrypted password in my hiera file, and it still fails, whenever I use a lookup for the password. I absolutely cannot have a plain text password in my manifest, so I need to solve this issue.

**Comment by ghoneycutt** [comment]
This question is not related to the module as it deals with how to use eyaml. Suggest looking through https://github.com/voxpupuli/hiera-eyaml
